# Autoperf Configuration File
#
# I've included all possible configurations, some commented.
#
# For detailed descriptions of httperf params, see:
#
# http://www.hpl.hp.com/research/linux/httperf/httperf-man-0.9.txt
#
# As for this, it's important to note that if an httperf param has
# a dash ('-') in it, it must be wrapped in quotes, either single
# or double. I use single in my examples below.

# display type
# display_format: console
# display_format: json
# display_format: csv

# configuration for display columns
#
# Note: this should be a list of symbols which match the result
# from HTTPerf.rb. That said, it can be symbol (like :rate) so
# long as you populate it yourself.
#
# display_columns:
# - :rate
# - :connection_rate_per_sec
# - :request_rate_per_sec
# - :connection_time_avg
# - :errors_total
# - :reply_status_5xx
# - :net_io_kb_sec
#
# :rate is specific to autoperf, see HTTPerf.rb for a list of
# keys: http://www.rubyops.net/gems/httperfrb
#
# for "console" and "csv", defines columns
# for "json", defines which results to include
#

## tee
#
# This is an httperf specific option which will force httperf to
# send it's STDOUT to the console as it runs, it defaults to false
#
tee: true

# The host
server: ypperf1.wc1.yellowpages.com

# The URI relative to the host root
# - use this without 'wlog'
#uri: /index.html

# The host port
port: 80

# Starting connection rate per second
low_rate: 100

# Highest connection rate per second
high_rate: 500

# Connection rate per second steps
# For the example config:
# [ 100, 150, 200, 250, 300, 350, 400, 450, 500 ]
rate_step: 50

# Run httperf verbose
verbose: true

# Replay file
#wlog: 'n,replay_log'

#session log with percentage
wsesslog: ['10,0,srp.log', '1,0,mip.log', '1,0,hom.log']

# Total number of connections
num-conns: 50

# See httperf docs
num-calls: 1

# See httperf docs
timeout: 5

# add-header adds an HTTP header
# If your test server is using HTTP basic auth, add a header like the following.
# To figure out what it should be use "curl -u user:password -v ..."
#
# add-header: '"Authorization: Basic AbC123xYz456==\n"'

###
# Other httperf options
#
# See httperf docs for details
###
# burst-length
# client
# close-with-reset
# debug
# failure-status
# hog
# http-version
# max-connections
# max-piped-calls
# method
# no-host-hdr
# period
# port
# print-reply
# print-request
# recv-buffer
# retry-on-failure
# send-buffer
# server-name
# session-cookies
# ssl
# ssl-ciphers
# ssl-no-reuse
# think-timeout
# wsess
# wsesslog
# wset

# vim: filetype=yaml:
